package com.yuan.newbeecopy.pojo;

public class AdminUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_admin_user.admin_user_id
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Long adminUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_admin_user.login_user_name
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private String loginUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_admin_user.login_password
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private String loginPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_admin_user.nick_name
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_admin_user.locked
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Byte locked;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_admin_user.admin_user_id
     *
     * @return the value of tb_newbee_mall_admin_user.admin_user_id
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Long getAdminUserId() {
        return adminUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_admin_user.admin_user_id
     *
     * @param adminUserId the value for tb_newbee_mall_admin_user.admin_user_id
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setAdminUserId(Long adminUserId) {
        this.adminUserId = adminUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_admin_user.login_user_name
     *
     * @return the value of tb_newbee_mall_admin_user.login_user_name
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public String getLoginUserName() {
        return loginUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_admin_user.login_user_name
     *
     * @param loginUserName the value for tb_newbee_mall_admin_user.login_user_name
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setLoginUserName(String loginUserName) {
        this.loginUserName = loginUserName == null ? null : loginUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_admin_user.login_password
     *
     * @return the value of tb_newbee_mall_admin_user.login_password
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_admin_user.login_password
     *
     * @param loginPassword the value for tb_newbee_mall_admin_user.login_password
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword == null ? null : loginPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_admin_user.nick_name
     *
     * @return the value of tb_newbee_mall_admin_user.nick_name
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_admin_user.nick_name
     *
     * @param nickName the value for tb_newbee_mall_admin_user.nick_name
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_admin_user.locked
     *
     * @return the value of tb_newbee_mall_admin_user.locked
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Byte getLocked() {
        return locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_admin_user.locked
     *
     * @param locked the value for tb_newbee_mall_admin_user.locked
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setLocked(Byte locked) {
        this.locked = locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_admin_user
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", adminUserId=").append(adminUserId);
        sb.append(", loginUserName=").append(loginUserName);
        sb.append(", loginPassword=").append(loginPassword);
        sb.append(", nickName=").append(nickName);
        sb.append(", locked=").append(locked);
        sb.append("]");
        return sb.toString();
    }
}