package com.yuan.newbeecopy.pojo;

import java.util.Date;

public class Carousel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_carousel.carousel_id
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Integer carouselId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_carousel.carousel_url
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private String carouselUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_carousel.redirect_url
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private String redirectUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_carousel.carousel_rank
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Integer carouselRank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_carousel.is_deleted
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Byte isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_carousel.create_time
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_carousel.create_user
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Integer createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_carousel.update_time
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_carousel.update_user
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Integer updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_carousel.carousel_id
     *
     * @return the value of tb_newbee_mall_carousel.carousel_id
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Integer getCarouselId() {
        return carouselId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_carousel.carousel_id
     *
     * @param carouselId the value for tb_newbee_mall_carousel.carousel_id
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setCarouselId(Integer carouselId) {
        this.carouselId = carouselId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_carousel.carousel_url
     *
     * @return the value of tb_newbee_mall_carousel.carousel_url
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public String getCarouselUrl() {
        return carouselUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_carousel.carousel_url
     *
     * @param carouselUrl the value for tb_newbee_mall_carousel.carousel_url
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setCarouselUrl(String carouselUrl) {
        this.carouselUrl = carouselUrl == null ? null : carouselUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_carousel.redirect_url
     *
     * @return the value of tb_newbee_mall_carousel.redirect_url
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public String getRedirectUrl() {
        return redirectUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_carousel.redirect_url
     *
     * @param redirectUrl the value for tb_newbee_mall_carousel.redirect_url
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setRedirectUrl(String redirectUrl) {
        this.redirectUrl = redirectUrl == null ? null : redirectUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_carousel.carousel_rank
     *
     * @return the value of tb_newbee_mall_carousel.carousel_rank
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Integer getCarouselRank() {
        return carouselRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_carousel.carousel_rank
     *
     * @param carouselRank the value for tb_newbee_mall_carousel.carousel_rank
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setCarouselRank(Integer carouselRank) {
        this.carouselRank = carouselRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_carousel.is_deleted
     *
     * @return the value of tb_newbee_mall_carousel.is_deleted
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_carousel.is_deleted
     *
     * @param isDeleted the value for tb_newbee_mall_carousel.is_deleted
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_carousel.create_time
     *
     * @return the value of tb_newbee_mall_carousel.create_time
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_carousel.create_time
     *
     * @param createTime the value for tb_newbee_mall_carousel.create_time
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_carousel.create_user
     *
     * @return the value of tb_newbee_mall_carousel.create_user
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_carousel.create_user
     *
     * @param createUser the value for tb_newbee_mall_carousel.create_user
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_carousel.update_time
     *
     * @return the value of tb_newbee_mall_carousel.update_time
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_carousel.update_time
     *
     * @param updateTime the value for tb_newbee_mall_carousel.update_time
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_carousel.update_user
     *
     * @return the value of tb_newbee_mall_carousel.update_user
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_carousel.update_user
     *
     * @param updateUser the value for tb_newbee_mall_carousel.update_user
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_carousel
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", carouselId=").append(carouselId);
        sb.append(", carouselUrl=").append(carouselUrl);
        sb.append(", redirectUrl=").append(redirectUrl);
        sb.append(", carouselRank=").append(carouselRank);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append("]");
        return sb.toString();
    }
}