package com.yuan.newbeecopy.pojo;

import java.util.Date;

public class GoodsCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_goods_category.category_id
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Long categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_goods_category.category_level
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Byte categoryLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_goods_category.parent_id
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_goods_category.category_name
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private String categoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_goods_category.category_rank
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Integer categoryRank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_goods_category.is_deleted
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Byte isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_goods_category.create_time
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_goods_category.create_user
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Integer createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_goods_category.update_time
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_goods_category.update_user
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Integer updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_goods_category.category_id
     *
     * @return the value of tb_newbee_mall_goods_category.category_id
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_goods_category.category_id
     *
     * @param categoryId the value for tb_newbee_mall_goods_category.category_id
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_goods_category.category_level
     *
     * @return the value of tb_newbee_mall_goods_category.category_level
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Byte getCategoryLevel() {
        return categoryLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_goods_category.category_level
     *
     * @param categoryLevel the value for tb_newbee_mall_goods_category.category_level
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setCategoryLevel(Byte categoryLevel) {
        this.categoryLevel = categoryLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_goods_category.parent_id
     *
     * @return the value of tb_newbee_mall_goods_category.parent_id
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_goods_category.parent_id
     *
     * @param parentId the value for tb_newbee_mall_goods_category.parent_id
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_goods_category.category_name
     *
     * @return the value of tb_newbee_mall_goods_category.category_name
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_goods_category.category_name
     *
     * @param categoryName the value for tb_newbee_mall_goods_category.category_name
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_goods_category.category_rank
     *
     * @return the value of tb_newbee_mall_goods_category.category_rank
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Integer getCategoryRank() {
        return categoryRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_goods_category.category_rank
     *
     * @param categoryRank the value for tb_newbee_mall_goods_category.category_rank
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setCategoryRank(Integer categoryRank) {
        this.categoryRank = categoryRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_goods_category.is_deleted
     *
     * @return the value of tb_newbee_mall_goods_category.is_deleted
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_goods_category.is_deleted
     *
     * @param isDeleted the value for tb_newbee_mall_goods_category.is_deleted
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_goods_category.create_time
     *
     * @return the value of tb_newbee_mall_goods_category.create_time
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_goods_category.create_time
     *
     * @param createTime the value for tb_newbee_mall_goods_category.create_time
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_goods_category.create_user
     *
     * @return the value of tb_newbee_mall_goods_category.create_user
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_goods_category.create_user
     *
     * @param createUser the value for tb_newbee_mall_goods_category.create_user
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_goods_category.update_time
     *
     * @return the value of tb_newbee_mall_goods_category.update_time
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_goods_category.update_time
     *
     * @param updateTime the value for tb_newbee_mall_goods_category.update_time
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_goods_category.update_user
     *
     * @return the value of tb_newbee_mall_goods_category.update_user
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_goods_category.update_user
     *
     * @param updateUser the value for tb_newbee_mall_goods_category.update_user
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_goods_category
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", categoryId=").append(categoryId);
        sb.append(", categoryLevel=").append(categoryLevel);
        sb.append(", parentId=").append(parentId);
        sb.append(", categoryName=").append(categoryName);
        sb.append(", categoryRank=").append(categoryRank);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append("]");
        return sb.toString();
    }
}