package com.yuan.newbeecopy.pojo;

import java.util.Date;

public class IndexConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_index_config.config_id
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Long configId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_index_config.config_name
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private String configName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_index_config.config_type
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Byte configType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_index_config.goods_id
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Long goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_index_config.redirect_url
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private String redirectUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_index_config.config_rank
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Integer configRank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_index_config.is_deleted
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Byte isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_index_config.create_time
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_index_config.create_user
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Integer createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_index_config.update_time
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_index_config.update_user
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Integer updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_index_config.config_id
     *
     * @return the value of tb_newbee_mall_index_config.config_id
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Long getConfigId() {
        return configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_index_config.config_id
     *
     * @param configId the value for tb_newbee_mall_index_config.config_id
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setConfigId(Long configId) {
        this.configId = configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_index_config.config_name
     *
     * @return the value of tb_newbee_mall_index_config.config_name
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public String getConfigName() {
        return configName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_index_config.config_name
     *
     * @param configName the value for tb_newbee_mall_index_config.config_name
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setConfigName(String configName) {
        this.configName = configName == null ? null : configName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_index_config.config_type
     *
     * @return the value of tb_newbee_mall_index_config.config_type
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Byte getConfigType() {
        return configType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_index_config.config_type
     *
     * @param configType the value for tb_newbee_mall_index_config.config_type
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setConfigType(Byte configType) {
        this.configType = configType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_index_config.goods_id
     *
     * @return the value of tb_newbee_mall_index_config.goods_id
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_index_config.goods_id
     *
     * @param goodsId the value for tb_newbee_mall_index_config.goods_id
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_index_config.redirect_url
     *
     * @return the value of tb_newbee_mall_index_config.redirect_url
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public String getRedirectUrl() {
        return redirectUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_index_config.redirect_url
     *
     * @param redirectUrl the value for tb_newbee_mall_index_config.redirect_url
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setRedirectUrl(String redirectUrl) {
        this.redirectUrl = redirectUrl == null ? null : redirectUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_index_config.config_rank
     *
     * @return the value of tb_newbee_mall_index_config.config_rank
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Integer getConfigRank() {
        return configRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_index_config.config_rank
     *
     * @param configRank the value for tb_newbee_mall_index_config.config_rank
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setConfigRank(Integer configRank) {
        this.configRank = configRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_index_config.is_deleted
     *
     * @return the value of tb_newbee_mall_index_config.is_deleted
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_index_config.is_deleted
     *
     * @param isDeleted the value for tb_newbee_mall_index_config.is_deleted
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_index_config.create_time
     *
     * @return the value of tb_newbee_mall_index_config.create_time
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_index_config.create_time
     *
     * @param createTime the value for tb_newbee_mall_index_config.create_time
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_index_config.create_user
     *
     * @return the value of tb_newbee_mall_index_config.create_user
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_index_config.create_user
     *
     * @param createUser the value for tb_newbee_mall_index_config.create_user
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_index_config.update_time
     *
     * @return the value of tb_newbee_mall_index_config.update_time
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_index_config.update_time
     *
     * @param updateTime the value for tb_newbee_mall_index_config.update_time
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_index_config.update_user
     *
     * @return the value of tb_newbee_mall_index_config.update_user
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_index_config.update_user
     *
     * @param updateUser the value for tb_newbee_mall_index_config.update_user
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_index_config
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", configId=").append(configId);
        sb.append(", configName=").append(configName);
        sb.append(", configType=").append(configType);
        sb.append(", goodsId=").append(goodsId);
        sb.append(", redirectUrl=").append(redirectUrl);
        sb.append(", configRank=").append(configRank);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append("]");
        return sb.toString();
    }
}