package com.yuan.newbeecopy.pojo;

import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_order.order_id
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_order.order_no
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_order.user_id
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_order.total_price
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Integer totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_order.pay_status
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Byte payStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_order.pay_type
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Byte payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_order.pay_time
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Date payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_order.order_status
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Byte orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_order.extra_info
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private String extraInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_order.is_deleted
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Byte isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_order.create_time
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_order.update_time
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_order.order_id
     *
     * @return the value of tb_newbee_mall_order.order_id
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_order.order_id
     *
     * @param orderId the value for tb_newbee_mall_order.order_id
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_order.order_no
     *
     * @return the value of tb_newbee_mall_order.order_no
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_order.order_no
     *
     * @param orderNo the value for tb_newbee_mall_order.order_no
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_order.user_id
     *
     * @return the value of tb_newbee_mall_order.user_id
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_order.user_id
     *
     * @param userId the value for tb_newbee_mall_order.user_id
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_order.total_price
     *
     * @return the value of tb_newbee_mall_order.total_price
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Integer getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_order.total_price
     *
     * @param totalPrice the value for tb_newbee_mall_order.total_price
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setTotalPrice(Integer totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_order.pay_status
     *
     * @return the value of tb_newbee_mall_order.pay_status
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Byte getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_order.pay_status
     *
     * @param payStatus the value for tb_newbee_mall_order.pay_status
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setPayStatus(Byte payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_order.pay_type
     *
     * @return the value of tb_newbee_mall_order.pay_type
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Byte getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_order.pay_type
     *
     * @param payType the value for tb_newbee_mall_order.pay_type
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setPayType(Byte payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_order.pay_time
     *
     * @return the value of tb_newbee_mall_order.pay_time
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_order.pay_time
     *
     * @param payTime the value for tb_newbee_mall_order.pay_time
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_order.order_status
     *
     * @return the value of tb_newbee_mall_order.order_status
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Byte getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_order.order_status
     *
     * @param orderStatus the value for tb_newbee_mall_order.order_status
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setOrderStatus(Byte orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_order.extra_info
     *
     * @return the value of tb_newbee_mall_order.extra_info
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public String getExtraInfo() {
        return extraInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_order.extra_info
     *
     * @param extraInfo the value for tb_newbee_mall_order.extra_info
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setExtraInfo(String extraInfo) {
        this.extraInfo = extraInfo == null ? null : extraInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_order.is_deleted
     *
     * @return the value of tb_newbee_mall_order.is_deleted
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_order.is_deleted
     *
     * @param isDeleted the value for tb_newbee_mall_order.is_deleted
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_order.create_time
     *
     * @return the value of tb_newbee_mall_order.create_time
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_order.create_time
     *
     * @param createTime the value for tb_newbee_mall_order.create_time
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_order.update_time
     *
     * @return the value of tb_newbee_mall_order.update_time
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_order.update_time
     *
     * @param updateTime the value for tb_newbee_mall_order.update_time
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_order
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderId=").append(orderId);
        sb.append(", orderNo=").append(orderNo);
        sb.append(", userId=").append(userId);
        sb.append(", totalPrice=").append(totalPrice);
        sb.append(", payStatus=").append(payStatus);
        sb.append(", payType=").append(payType);
        sb.append(", payTime=").append(payTime);
        sb.append(", orderStatus=").append(orderStatus);
        sb.append(", extraInfo=").append(extraInfo);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}