package com.yuan.newbeecopy.pojo;

public class OrderAddress {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_order_address.order_id
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_order_address.user_name
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_order_address.user_phone
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private String userPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_order_address.province_name
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private String provinceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_order_address.city_name
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private String cityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_order_address.region_name
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private String regionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_order_address.detail_address
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private String detailAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_order_address.order_id
     *
     * @return the value of tb_newbee_mall_order_address.order_id
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_order_address.order_id
     *
     * @param orderId the value for tb_newbee_mall_order_address.order_id
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_order_address.user_name
     *
     * @return the value of tb_newbee_mall_order_address.user_name
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_order_address.user_name
     *
     * @param userName the value for tb_newbee_mall_order_address.user_name
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_order_address.user_phone
     *
     * @return the value of tb_newbee_mall_order_address.user_phone
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_order_address.user_phone
     *
     * @param userPhone the value for tb_newbee_mall_order_address.user_phone
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_order_address.province_name
     *
     * @return the value of tb_newbee_mall_order_address.province_name
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_order_address.province_name
     *
     * @param provinceName the value for tb_newbee_mall_order_address.province_name
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_order_address.city_name
     *
     * @return the value of tb_newbee_mall_order_address.city_name
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_order_address.city_name
     *
     * @param cityName the value for tb_newbee_mall_order_address.city_name
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_order_address.region_name
     *
     * @return the value of tb_newbee_mall_order_address.region_name
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_order_address.region_name
     *
     * @param regionName the value for tb_newbee_mall_order_address.region_name
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setRegionName(String regionName) {
        this.regionName = regionName == null ? null : regionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_order_address.detail_address
     *
     * @return the value of tb_newbee_mall_order_address.detail_address
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public String getDetailAddress() {
        return detailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_order_address.detail_address
     *
     * @param detailAddress the value for tb_newbee_mall_order_address.detail_address
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setDetailAddress(String detailAddress) {
        this.detailAddress = detailAddress == null ? null : detailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_order_address
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderId=").append(orderId);
        sb.append(", userName=").append(userName);
        sb.append(", userPhone=").append(userPhone);
        sb.append(", provinceName=").append(provinceName);
        sb.append(", cityName=").append(cityName);
        sb.append(", regionName=").append(regionName);
        sb.append(", detailAddress=").append(detailAddress);
        sb.append("]");
        return sb.toString();
    }
}