package com.yuan.newbeecopy.pojo;

import java.util.Date;

public class UserAddress {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_user_address.address_id
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Long addressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_user_address.user_id
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_user_address.user_name
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_user_address.user_phone
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private String userPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_user_address.default_flag
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Byte defaultFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_user_address.province_name
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private String provinceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_user_address.city_name
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private String cityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_user_address.region_name
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private String regionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_user_address.detail_address
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private String detailAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_user_address.is_deleted
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Byte isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_user_address.create_time
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_user_address.update_time
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_user_address.address_id
     *
     * @return the value of tb_newbee_mall_user_address.address_id
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Long getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_user_address.address_id
     *
     * @param addressId the value for tb_newbee_mall_user_address.address_id
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setAddressId(Long addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_user_address.user_id
     *
     * @return the value of tb_newbee_mall_user_address.user_id
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_user_address.user_id
     *
     * @param userId the value for tb_newbee_mall_user_address.user_id
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_user_address.user_name
     *
     * @return the value of tb_newbee_mall_user_address.user_name
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_user_address.user_name
     *
     * @param userName the value for tb_newbee_mall_user_address.user_name
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_user_address.user_phone
     *
     * @return the value of tb_newbee_mall_user_address.user_phone
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_user_address.user_phone
     *
     * @param userPhone the value for tb_newbee_mall_user_address.user_phone
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_user_address.default_flag
     *
     * @return the value of tb_newbee_mall_user_address.default_flag
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Byte getDefaultFlag() {
        return defaultFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_user_address.default_flag
     *
     * @param defaultFlag the value for tb_newbee_mall_user_address.default_flag
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setDefaultFlag(Byte defaultFlag) {
        this.defaultFlag = defaultFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_user_address.province_name
     *
     * @return the value of tb_newbee_mall_user_address.province_name
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_user_address.province_name
     *
     * @param provinceName the value for tb_newbee_mall_user_address.province_name
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_user_address.city_name
     *
     * @return the value of tb_newbee_mall_user_address.city_name
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_user_address.city_name
     *
     * @param cityName the value for tb_newbee_mall_user_address.city_name
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_user_address.region_name
     *
     * @return the value of tb_newbee_mall_user_address.region_name
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_user_address.region_name
     *
     * @param regionName the value for tb_newbee_mall_user_address.region_name
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setRegionName(String regionName) {
        this.regionName = regionName == null ? null : regionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_user_address.detail_address
     *
     * @return the value of tb_newbee_mall_user_address.detail_address
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public String getDetailAddress() {
        return detailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_user_address.detail_address
     *
     * @param detailAddress the value for tb_newbee_mall_user_address.detail_address
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setDetailAddress(String detailAddress) {
        this.detailAddress = detailAddress == null ? null : detailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_user_address.is_deleted
     *
     * @return the value of tb_newbee_mall_user_address.is_deleted
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_user_address.is_deleted
     *
     * @param isDeleted the value for tb_newbee_mall_user_address.is_deleted
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_user_address.create_time
     *
     * @return the value of tb_newbee_mall_user_address.create_time
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_user_address.create_time
     *
     * @param createTime the value for tb_newbee_mall_user_address.create_time
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_user_address.update_time
     *
     * @return the value of tb_newbee_mall_user_address.update_time
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_user_address.update_time
     *
     * @param updateTime the value for tb_newbee_mall_user_address.update_time
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_user_address
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", addressId=").append(addressId);
        sb.append(", userId=").append(userId);
        sb.append(", userName=").append(userName);
        sb.append(", userPhone=").append(userPhone);
        sb.append(", defaultFlag=").append(defaultFlag);
        sb.append(", provinceName=").append(provinceName);
        sb.append(", cityName=").append(cityName);
        sb.append(", regionName=").append(regionName);
        sb.append(", detailAddress=").append(detailAddress);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}