package com.yuan.newbeecopy.pojo;

import java.util.Date;

public class UserToken {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_user_token.user_id
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_user_token.token
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_user_token.update_time
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_user_token.expire_time
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    private Date expireTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_user_token.user_id
     *
     * @return the value of tb_newbee_mall_user_token.user_id
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_user_token.user_id
     *
     * @param userId the value for tb_newbee_mall_user_token.user_id
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_user_token.token
     *
     * @return the value of tb_newbee_mall_user_token.token
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_user_token.token
     *
     * @param token the value for tb_newbee_mall_user_token.token
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_user_token.update_time
     *
     * @return the value of tb_newbee_mall_user_token.update_time
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_user_token.update_time
     *
     * @param updateTime the value for tb_newbee_mall_user_token.update_time
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_user_token.expire_time
     *
     * @return the value of tb_newbee_mall_user_token.expire_time
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_user_token.expire_time
     *
     * @param expireTime the value for tb_newbee_mall_user_token.expire_time
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_user_token
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", token=").append(token);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", expireTime=").append(expireTime);
        sb.append("]");
        return sb.toString();
    }
}