package com.yuan.newbeecopy.mapper;

import com.yuan.newbeecopy.pojo.AdminUserToken;
import com.yuan.newbeecopy.pojo.AdminUserTokenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminUserTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_admin_user_token
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    long countByExample(AdminUserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_admin_user_token
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    int deleteByExample(AdminUserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_admin_user_token
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    int deleteByPrimaryKey(Long adminUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_admin_user_token
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    int insert(AdminUserToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_admin_user_token
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    int insertSelective(AdminUserToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_admin_user_token
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    List<AdminUserToken> selectByExample(AdminUserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_admin_user_token
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    AdminUserToken selectByPrimaryKey(Long adminUserId);
    AdminUserToken selectByToken(String token);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_admin_user_token
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    int updateByExampleSelective(@Param("record") AdminUserToken record, @Param("example") AdminUserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_admin_user_token
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    int updateByExample(@Param("record") AdminUserToken record, @Param("example") AdminUserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_admin_user_token
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    int updateByPrimaryKeySelective(AdminUserToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_admin_user_token
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    int updateByPrimaryKey(AdminUserToken record);

}