package com.yuan.newbeecopy.mapper;

import com.yuan.newbeecopy.pojo.IndexConfig;
import com.yuan.newbeecopy.pojo.IndexConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IndexConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_index_config
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    long countByExample(IndexConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_index_config
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    int deleteByExample(IndexConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_index_config
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    int deleteByPrimaryKey(Long configId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_index_config
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    int insert(IndexConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_index_config
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    int insertSelective(IndexConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_index_config
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    List<IndexConfig> selectByExample(IndexConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_index_config
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    IndexConfig selectByPrimaryKey(Long configId);
    List<IndexConfig> findIndexConfigsByTypeAndNum(@Param("configType") int configType, @Param("number") int number);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_index_config
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    int updateByExampleSelective(@Param("record") IndexConfig record, @Param("example") IndexConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_index_config
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    int updateByExample(@Param("record") IndexConfig record, @Param("example") IndexConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_index_config
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    int updateByPrimaryKeySelective(IndexConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_index_config
     *
     * @mbg.generated Sat Jun 03 19:30:03 CST 2023
     */
    int updateByPrimaryKey(IndexConfig record);
}